import json

def generate_homey_script(flow_name, trigger_card_id, action_card_id):
    """
    Generates a HomeyScript (legacy) or Homey API script to create a flow.
    Note: HomeyScript runs inside the Homey environment.
    """
    
    # This is a template for the HomeyScript Code
    # It uses the Homey.flow.createFlow API which is available in the Homey Script context
    # or via the Web API if using a full app structure, but here we assume HomeyScript usage.
    
    js_code = f"""
// Auto-generated HomeyScript to create a flow
// Generated by generate_homey_script.py

async function createMyFlow() {{
    const flowName = "{flow_name}";
    
    console.log(`Creating flow: ${{flowName}}...`);

    try {{
        // Example Flow Structure
        // Note: You need actual Card IDs (uri) for triggers and actions.
        // You can find these by inspecting devices in the Homey Developer Tools or generic cards.
        
        const flow = await Homey.flow.createFlow({{
            name: flowName,
            enabled: true,
            // Example Trigger: "When flow is started" (generic)
            // Replace with actual card ID like 'homey:manager:flow:start'
            trigger: {{
                uri: '{trigger_card_id}', 
                id: 'start', // 'start' is often the ID for basic flow start triggers
                args: {{}}
            }},
            actions: [
                {{
                    // Example Action: Send a push notification (generic)
                    uri: '{action_card_id}', // e.g. 'homey:manager:mobile:push_text'
                    id: 'push_text',
                    args: {{
                        text: 'Flow created by script works!'
                    }}
                }}
            ]
        }});

        console.log('Flow created successfully!');
        console.log('Flow ID:', flow.id);
        return flow;
        
    }} catch (err) {{
        console.error('Error creating flow:', err);
        return false;
    }}
}}

// Execute the function
await createMyFlow();
"""
    return js_code

if __name__ == "__main__":
    # Example Usage
    # You would replace these URIs with real ones from your Homey Setup
    # e.g. 'homey:manager:flow' for system cards, or device URIs
    
    script_content = generate_homey_script(
        flow_name="Auto Generated Flow",
        trigger_card_id="homey:manager:flow", 
        action_card_id="homey:manager:mobile"
    )
    
    output_file = "create_flow_script.js"
    with open(output_file, "w") as f:
        f.write(script_content)
        
    print(f"✅ Generated HomeyScript saved to: {output_file}")
    print("📋 Copy the content of this file into a new HomeyScript in your Homey App to run it.")
